kind: pipeline
name: default

services:
  - name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      5432
    detach: true

steps:
- name: test
  image: rafaelrpbelo/ruby:2.6.3-std
  environment:
    BUNDLE_PATH: /bundle
    DB_HOST: db
    DB_USER: postgres
    DB_PASSWORD: postgres
    RAILS_ENV: test
  volumes:
  - name: bundle_cache
    path: /bundle
  commands:
  - bundle install --jobs=3 --retry=3 --without development,production
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec

volumes:
  - name: bundle_cache
    host:
      path: /etc/drone/bundles/hotelish/
