default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: hotelish_development

test:
  <<: *default
  database: hotelish_test

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>
  sslmode: require
